# Generated by Django 5.2.5 on 2025-08-18 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0004_remove_tariffserver_server_server_tariff'),
        ('users', '0003_telegramuser_is_active_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpn_key', models.TextField(blank=True, verbose_name='VPN key')),
                ('vpn_uuid', models.UUIDField(default=uuid.uuid4, verbose_name='Client UUID')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vpn', to='servers.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vpn', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'User VPN',
                'verbose_name_plural': 'User VPNs',
                'unique_together': {('user', 'server')},
            },
        ),
    ]
