# Generated by Django 5.2.6 on 2025-09-18 20:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservpn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания записи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uservpn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления записи'),
        ),
    ]
