# Generated by Django 5.2.6 on 2025-09-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0002_uservpn_created_at_uservpn_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservpn',
            unique_together=set(),
        ),
    ]
