# Generated by Django 5.2.6 on 2026-04-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vpn', '0003_alter_uservpn_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservpn',
            name='vless_links',
            field=models.JSONField(blank=True, default=list, verbose_name='VLESS links'),
        ),
    ]
