# Generated by Django 5.2.6 on 2026-08-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0004_uservpn_sub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservpn',
            name='device_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Лимит устройств'),
        ),
    ]
