# Generated by Django 5.2.6 on 2025-09-17 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='VPN url')),
                ('valid_until', models.DateTimeField(verbose_name='Действительно до')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='servers.server')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
