# Generated by Django 5.2.6 on 2026-08-12 18:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('users', '0004_alter_telegramuser_username'),
        ('vpn', '0005_uservpn_device_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionDeviceReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'last_reset_at',
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последний сброс устройств'),
                ),
                (
                    'telegram_user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='device_reset',
                        to='users.telegramuser',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Сброс устройств',
                'verbose_name_plural': 'Сбросы устройств',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hwid', models.CharField(max_length=64, verbose_name='Идентификатор устройства')),
                ('device_os', models.CharField(blank=True, default='', max_length=32, verbose_name='ОС устройства')),
                ('os_version', models.CharField(blank=True, default='', max_length=32, verbose_name='Версия ОС')),
                (
                    'device_model',
                    models.CharField(blank=True, default='', max_length=64, verbose_name='Модель устройства'),
                ),
                ('user_agent', models.CharField(blank=True, default='', max_length=128, verbose_name='User-Agent')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='Первое обращение')),
                (
                    'last_seen_at',
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее обращение'),
                ),
                (
                    'subscription',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='vpn.uservpn'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Устройство подписки',
                'verbose_name_plural': 'Устройства подписок',
                'constraints': [
                    models.UniqueConstraint(fields=('subscription', 'hwid'), name='unique_subscription_device')
                ],
            },
        ),
    ]
