# Generated by Django 5.2.6 on 2026-08-12 18:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptiondevicereset_subscriptiondevice'),
        ('users', '0004_alter_telegramuser_username'),
        ('vpn', '0005_uservpn_device_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionDeviceBindingWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'opened_at',
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name='Окно привязки открыто'),
                ),
                (
                    'telegram_user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='device_binding_window',
                        to='users.telegramuser',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Окно привязки устройств',
                'verbose_name_plural': 'Окна привязки устройств',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionDeviceRegistrationRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'period_started_at',
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало периода'),
                ),
                ('registrations', models.PositiveIntegerField(default=0, verbose_name='Регистраций за период')),
                (
                    'subscription',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='device_registration_rate',
                        to='vpn.uservpn',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Частота привязок подписки',
                'verbose_name_plural': 'Частоты привязок подписок',
            },
        ),
    ]
