# Generated by Django 5.2.6 on 2026-08-13 22:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptiondevicebindingwindow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MirrorEndpointLiveness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=253, verbose_name='Адрес эндпоинта')),
                ('port', models.PositiveIntegerField(verbose_name='Порт')),
                ('alive', models.BooleanField(default=False, verbose_name='Отвечает')),
                ('error_class', models.CharField(blank=True, default='', max_length=64, verbose_name='Класс отказа')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Проверено')),
            ],
            options={
                'verbose_name': 'Живость зеркального эндпоинта',
                'verbose_name_plural': 'Живость зеркальных эндпоинтов',
                'constraints': [
                    models.UniqueConstraint(fields=('host', 'port'), name='unique_mirror_endpoint_liveness')
                ],
            },
        ),
    ]
