# Generated by Django 5.2.6 on 2026-08-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_mirrorendpointliveness'),
    ]

    operations = [
        migrations.AddField(
            model_name='mirrorendpointliveness',
            name='probed_from',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Источник замера'),
        ),
    ]
