# Generated by Django 5.2.5 on 2025-08-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Наименование сервера')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP сервера')),
                ('ssh_username', models.CharField(blank=True, max_length=255, verbose_name='SSH логин')),
                ('ssh_password', models.CharField(blank=True, max_length=255, verbose_name='SSH пароль')),
                ('vpn_username', models.CharField(blank=True, max_length=255, verbose_name='Username 3x-ui')),
                ('vpn_password', models.CharField(blank=True, max_length=255, verbose_name='Password 3x-ui')),
                ('vpn_key', models.CharField(blank=True, max_length=255, verbose_name='Key 3x-ui')),
                ('vpn_url', models.CharField(blank=True, max_length=255, verbose_name='URL 3x-ui')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи')),
            ],
            options={
                'verbose_name': 'Информация о сервере',
                'verbose_name_plural': 'Информация о серверах',
            },
        ),
    ]
