# Generated by Django 5.2.6 on 2025-09-17 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TariffServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование тарифа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена, руб')),
            ],
            options={
                'verbose_name': 'Информация о тарифе',
                'verbose_name_plural': 'Информация о тарифах',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Наименование сервера')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP сервера для ssh подключения')),
                ('ssh_username', models.CharField(max_length=255, verbose_name='SSH логин')),
                ('ssh_password', models.CharField(max_length=255, verbose_name='SSH пароль')),
                ('vpn_username', models.CharField(max_length=255, verbose_name='Username 3x-ui')),
                ('vpn_password', models.CharField(max_length=255, verbose_name='Password 3x-ui')),
                ('vpn_key', models.CharField(max_length=255, verbose_name='Key 3x-ui')),
                ('vpn_url', models.CharField(blank=True, max_length=255, verbose_name='URL 3x-ui')),
                ('client_vpn_host', models.CharField(blank=True, max_length=255, verbose_name='VPN хост, к которому будут подключаться клиенты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи')),
                ('inbound_id', models.IntegerField(default=1, verbose_name='Inbound ID')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servers', to='servers.tariffserver')),
            ],
            options={
                'verbose_name': 'Информация о сервере',
                'verbose_name_plural': 'Информация о серверах',
            },
        ),
    ]
