# Generated by Django 5.2.5 on 2025-08-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP сервера для ssh подключения'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ssh_password',
            field=models.CharField(max_length=255, verbose_name='SSH пароль'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ssh_username',
            field=models.CharField(max_length=255, verbose_name='SSH логин'),
        ),
        migrations.AlterField(
            model_name='server',
            name='vpn_key',
            field=models.CharField(max_length=255, verbose_name='Key 3x-ui'),
        ),
        migrations.AlterField(
            model_name='server',
            name='vpn_password',
            field=models.CharField(max_length=255, verbose_name='Password 3x-ui'),
        ),
        migrations.AlterField(
            model_name='server',
            name='vpn_username',
            field=models.CharField(max_length=255, verbose_name='Username 3x-ui'),
        ),
    ]
