# Generated by Django 5.2.6 on 2026-04-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='inbound_id_grpc',
            field=models.IntegerField(default=1, verbose_name='Inbound ID (gRPC)'),
        ),
        migrations.AddField(
            model_name='server',
            name='inbound_id_http',
            field=models.IntegerField(default=1, verbose_name='Inbound ID (HTTP)'),
        ),
        migrations.AddField(
            model_name='server',
            name='inbound_id_udp',
            field=models.IntegerField(default=1, verbose_name='Inbound ID (UDP)'),
        ),
    ]
