# Generated by Django 5.2.5 on 2025-08-11 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_alter_server_ip_address_alter_server_ssh_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование тарифа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена, руб')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariffs', to='servers.server')),
            ],
            options={
                'verbose_name': 'Информация о тарифе',
                'verbose_name_plural': 'Информация о тарифах',
            },
        ),
    ]
