# Generated by Django 5.2.5 on 2025-08-18 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_tariffserver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariffserver',
            name='server',
        ),
        migrations.AddField(
            model_name='server',
            name='tariff',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='servers', to='servers.tariffserver'),
            preserve_default=False,
        ),
    ]
