# Generated by Django 5.2.5 on 2025-08-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_remove_tariffserver_server_server_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='inbound_id',
            field=models.IntegerField(default=1, verbose_name='Inbound ID'),
        ),
    ]
