# Generated by Django 5.2.5 on 2025-08-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_server_inbound_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='client_vpn_host',
            field=models.CharField(blank=True, max_length=255, verbose_name='VPN хост, к которому будут подключаться клиенты'),
        ),
    ]
