# Generated by Django 5.2.6 on 2025-09-17 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='users.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидание'), ('SUCCESS', 'Успешно'), ('FAILED', 'Неуспешно')], max_length=7, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('source', models.CharField(choices=[('YOUMONEY', 'Юмани'), ('PROMO', 'Промо-баланс'), ('EVERYDAY_SYSTEM', 'Ежедневное списание')], max_length=15, verbose_name='Источник')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'constraints': [models.UniqueConstraint(condition=models.Q(('source', 'PROMO')), fields=('user',), name='unique_promo_transaction_per_user')],
            },
        ),
    ]
