# Generated by Django 5.2.5 on 2025-08-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('FREEKASSA', 'Фрикасса'), ('PROMO', 'Промо-баланс')], default='', max_length=9, verbose_name='Источник'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидание'), ('SUCCESS', 'Успешно'), ('FAILED', 'Неуспешно')], max_length=7, verbose_name='Статус'),
        ),
    ]
