# Generated by Django 5.2.6 on 2025-09-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('YOUMONEY', 'Юмани'), ('PROMO', 'Промо-баланс'), ('EVERYDAY_SYSTEM', 'Ежедневное списание'), ('BUY', 'Покупка'), ('MANUAL', 'Руками проставили')], default='MANUAL', max_length=15, verbose_name='Источник'),
        ),
    ]
