# Generated by Django 5.2.6 on 2026-01-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_transaction_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('YOUMONEY', 'Юмани'), ('PROMO', 'Промо-баланс'), ('EVERYDAY_SYSTEM', 'Ежедневное списание'), ('BUY', 'Покупка'), ('MANUAL', 'Руками проставили'), ('REFERRAL', 'Реферальная система')], default='MANUAL', max_length=15, verbose_name='Источник'),
        ),
    ]
