# Generated by Django 5.2.6 on 2026-01-12 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_transaction_source'),
        ('users', '0003_alter_telegramuser_referral_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='from_referral_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_transactions', to='users.telegramuser'),
        ),
    ]
