# Generated by Django 5.2.6 on 2025-09-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.TextField(blank=True, null=True, verbose_name='Telegram Username'),
        ),
    ]
