# Generated by Django 5.2.5 on 2025-08-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_telegramuser_referral_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_active_promo',
            field=models.BooleanField(default=False, verbose_name='Был активирован промо'),
        ),
    ]
