# Generated by Django 5.2.6 on 2026-01-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_telegramuser_referral_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.TextField(blank=True, default='', verbose_name='Telegram Username'),
            preserve_default=False,
        ),
    ]
