"""
Django settings for bot project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ
from celery.schedules import crontab


env = environ.Env()
environ.Env.read_env(env_file='.environment')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h+gcq#-1tm#01(qh5_dldokr&236ueo9g-#loi(y$=u&s@&xc3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', '109.172.30.146']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'apps.payments.apps.PaymentsConfig',
    'apps.servers',
    'apps.subscriptions',
    'apps.telegram_bot',
    'apps.users',
    'apps.vpn',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': env.db(
        'DATABASE_URL',
        default='postgres://vpnbot:vpnbot@:5432/vpnbot',
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


TELEGRAM_BOT_TOKEN = env.str('TELEGRAM_BOT_TOKEN', '')
YOUMONEY_TOKEN = env.str('YOUMONEY_TOKEN', '')

# Redis / Celery
# Default includes password for local/docker parity; override via env in production if needed
REDIS_URL = env.str('REDIS_URL', 'redis://:MyRedis2025@localhost:6379/0')

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = env.str('TIME_ZONE', 'UTC')
CELERY_ALWAYS_EAGER = env.bool('CELERY_ALWAYS_EAGER', False)

# More resilient Redis/Celery connection handling
# Helps survive Redis restarts/UNBLOCKED events by retrying and keeping sockets alive
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_HEARTBEAT = 30
CELERY_BROKER_POOL_LIMIT = None  # Unlimited; let redis-py pool manage limits
CELERY_REDIS_MAX_CONNECTIONS = 20
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 3600,  # Re-queue tasks if worker dies while processing
    'socket_keepalive': True,
    'retry_on_timeout': True,
    'socket_connect_timeout': 5,
    'socket_timeout': 5,
    'health_check_interval': 30,
}
CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS = {
    'retry_on_timeout': True,
    'socket_keepalive': True,
    'socket_connect_timeout': 5,
    'socket_timeout': 5,
    'health_check_interval': 30,
}

CELERY_BEAT_SCHEDULE = {
    'update_user_vpn_daily': {
        'task': 'apps.subscriptions.tasks.update_user_vpn',
        'schedule': crontab(minute=0, hour=0),  # 00:00 UTC daily
    },
}

REFERRAL_PERCENT = env.int('REFERRAL_PERCENT', 30)

# Максимальное количество ключей для одного юзера
MAX_KEYS = env.int('MAX_KEYS', 3)

# Количество IP для одного клиента
LIMIT_IP = env.int('LIMIT_IP', 2)

BOT_LINK = env.str('BOT_LINK', 'https://t.me/SpecialVPNbot')

SUBSCRIPTION_BASE_URL = env.str('SUBSCRIPTION_BASE_URL', 'http://127.0.0.1:8000')
