# Generated by Django 5.2.6 on 2026-08-12 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0006_transaction_daily_charge_idempotency'),
        ('users', '0004_alter_telegramuser_username'),
        ('vpn', '0005_uservpn_device_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=128, unique=True, verbose_name='Ключ идемпотентности')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='Время события')),
                ('effective_date', models.DateField(verbose_name='Дата, к которой относится событие')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Время записи')),
                (
                    'origin',
                    models.CharField(
                        choices=[('LIVE', 'Записано в момент события'), ('BACKFILL', 'Восстановлено из истории')],
                        default='LIVE',
                        max_length=8,
                    ),
                ),
                (
                    'step',
                    models.CharField(
                        choices=[
                            ('BALANCE_SCREEN_SHOWN', 'Открыт экран пополнения'),
                            ('PROMO_CLAIMED', 'Забран промо-баланс'),
                            ('TOPUP_PLAN_CHOSEN', 'Выбран срок пополнения'),
                            ('INVOICE_SENT', 'Отправлен счёт'),
                            ('PRE_CHECKOUT_APPROVED', 'Пройден pre-checkout'),
                            ('PAYMENT_COMPLETED', 'Платёж завершён'),
                            ('SUBSCRIPTION_CREATED', 'Создана подписка'),
                            ('SUBSCRIPTION_REFUSED_NO_FUNDS', 'Отказ в подписке из-за баланса'),
                            ('SUBSCRIPTION_REMOVED', 'Подписка удалена пользователем'),
                            ('SUBSCRIPTION_DISABLED_NO_FUNDS', 'Подписка отключена биллингом'),
                            ('ACCOUNT_BILLING_LAPSED', 'Аккаунт перестал списываться'),
                            ('ACCOUNT_BILLING_RESUMED', 'Аккаунт снова начал списываться'),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    'amount',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма шага'
                    ),
                ),
                ('days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок шага в днях')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='funnel_events',
                        to='users.telegramuser',
                    ),
                ),
                (
                    'user_vpn',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='funnel_events',
                        to='vpn.uservpn',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Событие воронки',
                'verbose_name_plural': 'События воронки',
                'indexes': [
                    models.Index(fields=['effective_date', 'step'], name='funnel_event_date_step_idx'),
                    models.Index(fields=['user', 'effective_date'], name='funnel_event_user_date_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='MoneyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=128, unique=True, verbose_name='Ключ идемпотентности')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='Время события')),
                ('effective_date', models.DateField(verbose_name='Дата, к которой относится событие')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Время записи')),
                (
                    'origin',
                    models.CharField(
                        choices=[('LIVE', 'Записано в момент события'), ('BACKFILL', 'Восстановлено из истории')],
                        default='LIVE',
                        max_length=8,
                    ),
                ),
                ('source', models.CharField(max_length=15, verbose_name='Источник строки')),
                ('status', models.CharField(max_length=7, verbose_name='Статус строки')),
                (
                    'kind',
                    models.CharField(
                        choices=[
                            ('TOPUP', 'Пополнение через платёжного провайдера'),
                            ('SIGNUP_PROMO', 'Промо-баланс новичка'),
                            ('OUTAGE_COMPENSATION', 'Компенсация простоя'),
                            ('MANUAL_CREDIT', 'Начисление руками'),
                            ('MANUAL_ADJUSTMENT', 'Списание руками'),
                            ('REFERRAL_PAYOUT', 'Реферальная выплата'),
                            ('DAILY_CHARGE', 'Ежедневное списание'),
                            ('SUBSCRIPTION_PURCHASE', 'Плата за новую подписку'),
                            ('REVERSAL', 'Обратная строка к списанию или начислению'),
                            ('NO_OP', 'Нулевая строка'),
                            ('UNCLASSIFIED', 'Источник не известен таксономии'),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    'economic_class',
                    models.CharField(
                        choices=[
                            ('CASH_IN', 'Пришли реальные деньги'),
                            ('REVENUE', 'Признанная выручка'),
                            ('CREDIT_GRANTED', 'Выдан баланс бесплатно'),
                            ('PAYOUT', 'Выплата партнёру'),
                            ('ADJUSTMENT', 'Внутренняя корректировка'),
                            ('UNKNOWN', 'Не классифицировано'),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    'cash_basis',
                    models.CharField(
                        choices=[
                            ('MEASURED', 'Сумма платежа известна от места вызова'),
                            ('DERIVED', 'Восстановлена из начисленного по лестнице бонусов'),
                            ('NONE', 'Денег не было по определению'),
                            ('UNKNOWN', 'Деньги могли пройти мимо системы, сумма невосстановима'),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    'date_basis',
                    models.CharField(
                        choices=[
                            ('CHARGE_DATE', 'Ключ идемпотентности ежедневного списания'),
                            ('CREATED_AT', 'Момент создания строки'),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    'balance_delta',
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Влияние на баланс'),
                ),
                (
                    'cash_amount',
                    models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Полученные деньги'),
                ),
                (
                    'revenue_amount',
                    models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Признанная выручка'),
                ),
                (
                    'credit_amount',
                    models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Выданный баланс'),
                ),
                (
                    'payout_amount',
                    models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Выплата партнёру'),
                ),
                (
                    'referred_user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='referral_money_events',
                        to='users.telegramuser',
                    ),
                ),
                (
                    'transaction',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='money_events',
                        to='payments.transaction',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='money_events',
                        to='users.telegramuser',
                    ),
                ),
                (
                    'user_vpn',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='money_events',
                        to='vpn.uservpn',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Денежное событие',
                'verbose_name_plural': 'Денежные события',
                'indexes': [
                    models.Index(fields=['effective_date', 'economic_class'], name='money_event_date_class_idx'),
                    models.Index(fields=['user', 'effective_date'], name='money_event_user_date_idx'),
                    models.Index(fields=['kind', 'effective_date'], name='money_event_kind_date_idx'),
                ],
            },
        ),
    ]
