# Generated by Django 5.2.6 on 2025-09-18 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Краткое описание рассылки', max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(help_text='Текст сообщения для рассылки', verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='draft', max_length=20, verbose_name='Статус')),
                ('total_users', models.PositiveIntegerField(default=0, help_text='Общее количество пользователей для рассылки', verbose_name='Всего пользователей')),
                ('sent_count', models.PositiveIntegerField(default=0, help_text='Количество успешно отправленных сообщений', verbose_name='Отправлено')),
                ('failed_count', models.PositiveIntegerField(default=0, help_text='Количество неудачных отправок', verbose_name='Ошибок')),
                ('error_message', models.TextField(blank=True, help_text='Детали ошибки при отправке', null=True, verbose_name='Сообщение об ошибке')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Время для отложенной отправки (оставьте пустым для немедленной отправки)', null=True, verbose_name='Запланировано на')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Время фактической отправки', null=True, verbose_name='Отправлено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
