# Generated by Django 5.2.6 on 2025-09-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='photo',
            field=models.ImageField(blank=True, help_text='Необязательно: изображение, которое будет отправлено вместе с текстом', null=True, upload_to='broadcasts/', verbose_name='Фото'),
        ),
    ]
