# Generated by Django 5.2.6 on 2026-08-12 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_broadcast_confirmation_snapshot'),
        ('users', '0004_alter_telegramuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='support_prompt',
                        to='users.telegramuser',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ожидание сообщения в поддержку',
                'verbose_name_plural': 'Ожидания сообщений в поддержку',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.TextField(blank=True, verbose_name='Telegram Username')),
                ('topic_id', models.BigIntegerField(blank=True, null=True, verbose_name='Идентификатор темы')),
                (
                    'status',
                    models.CharField(
                        choices=[('open', 'Открыт'), ('closed', 'Закрыт')],
                        default='open',
                        max_length=16,
                        verbose_name='Статус',
                    ),
                ),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Тема обращения')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Служебные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыто')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='support_tickets',
                        to='users.telegramuser',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Обращение в поддержку',
                'verbose_name_plural': 'Обращения в поддержку',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['topic_id', 'status'], name='telegram_bo_topic_i_745ca8_idx')],
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('status', 'open')), fields=('user',), name='unique_open_support_ticket'
                    )
                ],
            },
        ),
    ]
