# Generated by Django 5.2.6 on 2026-08-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0007_supportticket_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='audience',
            field=models.CharField(
                choices=[
                    ('subscription_ready', 'Владельцы готовых оплаченных подписок'),
                    ('without_subscription', 'Все, кроме владельцев подписок'),
                    ('all', 'Все пользователи'),
                ],
                default='subscription_ready',
                help_text='Получатели фиксируются при первом запуске отправки.',
                max_length=32,
                verbose_name='Аудитория',
            ),
        ),
    ]
